### ISSUE TITLE
python3 not support

### ISSUE THREAD

**Issue by techteams0** [TeamDefronix/Cyberonix#41]
└─$ sudo python3 setup.py
[sudo] password for techteams: 
Traceback (most recent call last):
  File "/home/techteams/Cyberonix/setup.py", line 5, in <module>
    import cyberonix
  File "/home/techteams/Cyberonix/cyberonix.py", line 4, in <module>
    from main import *
  File "/home/techteams/Cyberonix/main/arguments.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by THECH13F** [comment]
please install requirements file to run that

**Comment by 0xMrR0b0t** [comment]
no need to write python 3 just write python setup.py
