### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by cdworld0** [TeamDefronix/Cyberonix#42]
Traceback (most recent call last):
  File "/home/cdworld/Cyberonix/cyberonix.py", line 4, in <module>
    from main import *
  File "/home/cdworld/Cyberonix/main/arguments.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Traceback (most recent call last):
  File "/home/cdworld/Cyberonix/cyberonix.py", line 4, in <module>
    from main import *
  File "/home/cdworld/Cyberonix/main/arguments.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

I have allerady downloaded selenium

**Comment by b14ckky** [comment]
If you have pip installed you can install selenium like so.
```
pip install selenium
```
or depending on your permissions:
```
sudo pip install selenium
```
For python3:
```
sudo pip3 install selenium
```
