### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by kamlesh-rkj** [TeamDefronix/Cyberonix#44]
┌──(kali㉿kali)-[~/Desktop/Cyberonix]
└─$ sudo cyberonix        
[sudo] password for kali: 
Traceback (most recent call last):
  File "/home/kali/Desktop/Cyberonix/./setup.py", line 5, in <module>
    import cyberonix
  File "/home/kali/Desktop/Cyberonix/cyberonix.py", line 4, in <module>
    from main import *
  File "/home/kali/Desktop/Cyberonix/main/arguments.py", line 1, in <module>
    import dns.resolver, requests, socket, os, time
  File "/usr/local/lib/python3.11/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python3.11/dist-packages/requests/utils.py", line 30, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/local/lib/python3.11/dist-packages/requests/cookies.py", line 164, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by kamlesh-rkj** [comment]
this issue is raise by python 3.11.5 there are some change in syntax 
by changing one import statement it's work fine
