### ISSUE TITLE
Kali Linux Installation Problem 

### ISSUE THREAD

**Issue by MouhyiHacker** [TeamDefronix/Cyberonix#49]
ERROR: Cannot uninstall dnspython 2.6.0, RECORD file not found. Hint: The package was installed by debian.

**Comment by defronixpro** [comment]
please add a screenshot to it

**Comment by MouhyiHacker** [comment]
I Edit Code And Somethings In My Kali Now It Works Thanks For Your Respond

**Comment by Harshit9695** [comment]
getting an error 


Traceback (most recent call last):
  File "/home/patty/Desktop/Cyberonix/cyberonix.py", line 4, in <module>
    from main.tools import banner,colors,template,Recommended_Tool,run_on_browser
  File "/home/patty/Desktop/Cyberonix/main/tools/template.py", line 1, in <module>
    from main.tools import banner, waiting, writeup, colors, run_on_browser, Recommended_Tool
  File "/home/patty/Desktop/Cyberonix/main/tools/Recommended_Tool.py", line 1, in <module>
    from main.tools import banner, waiting, writeup, colors, run_on_browser, Recommended_Tool,template, Anonymity
  File "/home/patty/Desktop/Cyberonix/main/tools/Anonymity.py", line 3, in <module>
    import requests
  File "/usr/local/lib/python3.11/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python3.11/dist-packages/requests/utils.py", line 30, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/local/lib/python3.11/dist-packages/requests/cookies.py", line 164, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by MouhyiHacker** [comment]
Try These, python3 python or ./ To run the code

**Comment by Hadi493** [comment]
![Screenshot from 2024-06-01 21-52-42](https://github.com/TeamDefronix/Cyberonix/assets/145929946/6f26f7a6-b003-4730-9d09-270c98362059)

**Comment by THECH13F** [comment]
please run ```python setup.py``` first then run the tool

**Comment by Hadi493** [comment]
yes sir but not work
